import Logo from "@/components/Layout/Header/Logo";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <div className="content-container flex justify-between items-center mx-auto px-10  py-10">
          <Logo />
        </div>
        <div className="flex flex-col items-start justify-start min-w-full min-h-full pt-10 pb-4 m-auto">
          <main className="relative hero-area w-full flex-col item-center justify-center p-0 m-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
